# Generated by Django 4.2.8 on 2024-04-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countsite',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
