# Generated by Django 4.2.8 on 2024-05-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_countsite_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countsite',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Between -5 and 5 usually', null=True),
        ),
        migrations.AlterField(
            model_name='countsite',
            name='link_url',
            field=models.CharField(blank=True, help_text='Link for an image (you can use https://postimages.org)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='countsite',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Between -75 and -85 usually', null=True),
        ),
        migrations.AlterField(
            model_name='countsite',
            name='phone_number',
            field=models.CharField(blank=True, help_text='One number, Ecuadorian phones only', max_length=10, null=True),
        ),
    ]
