# Generated by Django 4.2.8 on 2024-05-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_alter_countsite_latitude_alter_countsite_link_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countsite',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='countsite',
            name='picture_url',
            field=models.CharField(blank=True, help_text='Link for an image (you can use https://postimages.org)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='countsite',
            name='link_url',
            field=models.CharField(blank=True, help_text='Link for a googleform or whatever', max_length=100, null=True),
        ),
    ]
